# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '13.x'
  displayName: 'Install Node.js'
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: client-side/angular
    verbose: false
- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    workingDir: client-side/angular
    verbose: false
    customCommand: 'cache clean --force'
  enabled: false

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    workingDir: client-side/angular
    verbose: false
    customCommand: 'run build'

- task: ArchiveFiles@2
  displayName: 'Archive dist directory'
  inputs:
    rootFolderOrFile: client-side/angular/dist
    archiveFile: dist.zip
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist.zip'
    ArtifactName: 'Rxweb-Clientside-angular'
    publishLocation: 'Container'

